### ISSUE TITLE
Use Picocli as Command Line Tool

### ISSUE THREAD

**Issue by aalbahem** [READ-BioMed/readbiomed-pathogen-annotator#1]
We often need to parse arguments from the command line for running an experiment. I have surveyed many tools and found that [Picocli](https://picocli.info) is the one with a more active and wider community.

**Comment by ajjimeno** [comment]
Thanks Ameer. It looks quite complete and easy to use.

**Comment by ajjimeno** [comment]
Picocli is used in all classes where command line arguments are needed.
